#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f *.vcd

#run Verilator to translate Verilog into C++, including C++ testbench
<<<<<<<< HEAD:rtl/run.sh
verilator -Wall --cc --trace top.sv --exe top_tb.cpp
========
verilator -Wall --cc --trace  top.sv --exe f1_tb.cpp
>>>>>>>> 0769af59e61be4a34d42736fc0d582a54e5128fc:rtl/f1run.sh

#build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtop.mk Vtop

#run executable simlulation file
obj_dir/Vtop