#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f two_way.vcd

#run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace direct_cache.sv --exe top_tb.cpp

#build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtwo_way.mk Vtwo_way

#run executable simlulation file
obj_dir/Vtwo_way