#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f data_memory_cache.vcd

#run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace data_memory_cache.sv --exe top_tb.cpp

#build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vdata_memory_cache.mk Vdata_memory_cache

#run executable simlulation file
obj_dir/Vdata_memory_cache