#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f direct_cache.vcd

#run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace direct_cache.sv --exe direct_cache_tb.cpp

#build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vdirect_cache.mk Vdirect_cache

#run executable simlulation file
obj_dir/Vdirect_cache