#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f cache_top.vcd

#run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace cache_top.sv --exe direct_cache_tb.cpp

#build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vcache_top.mk Vcache_top

#run executable simlulation file
obj_dir/Vcache_top